#define BLACK        0
#define RED          1
#define GREEN        2
#define YELLOW       3
#define BLUE         4
#define MAGENTA      5
#define CYAN         6
#define WHITE        7
#define GRAY         8
#define BRIGHT_RED   9
#define BRIGHT_GREEN 10
#define BRIGHT_YELLOW 11
#define BRIGHT_BLUE  12
#define BRIGHT_MAGENTA 13
#define BRIGHT_CYAN  14
#define BRIGHT_WHITE 15
#define ORANGE       208
#define DEEP_ORANGE  210
#define DEEP_RED     124
#define DEEP_GREEN   28
#define DEEP_YELLOW  136
#define DEEP_BLUE    17
#define DEEP_MAGENTA 88
#define DEEP_CYAN    24
#define DARK_GRAY    239
#define LIGHT_GRAY   250