#include "creditsTile.h"

void runCreditsTile(){
    char cInput=' ';
    int nPadding=6;
    
    printRepeatedly(nPadding,"\n");
    printRepeatedly(nPadding,"\t");
    printf("╔════════════════════════════════╗\n");
    printRepeatedly(nPadding,"\t");
    printf("║                                ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║     THANK YOU FOR PLAYING!     ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║          ELDEN ROGUE           ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║                                ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║ ---- -  - DEVELOPERS -  - ---- ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║          Elomina, Zivv         ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║         Naranjo, Johann        ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║                                ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║ ---- -  SPECIAL THANKS  - ---- ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║          Sadio, Megan          ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║       Montuerto, Yzabelle      ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║                                ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║   For expanding horizons and   ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║     inspiring a generation.    ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║                                ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║ --- THANK YOU & GOOD LUCK! --- ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║     Prof. Espulgar, Candy      ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║                                ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║          On your PHD           ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║      and future endeavors      ║\n");
    printRepeatedly(nPadding,"\t");
    printf("║                                ║\n");
    printRepeatedly(nPadding,"\t");
    printf("╚════════════════════════════════╝\n");
    printRepeatedly(nPadding,"\t");
    printf("(0) to continue\n");
    printRepeatedly(nPadding,"\t");
    printf("> ");
    scanf(" %c", &cInput);
    printRepeatedly(3,"\n");
}